### ISSUE TITLE
[Question] What was the initiative here?

### ISSUE THREAD

**Issue by tomislacker** [mGageTechOps/ansible-role-efs#4]
- Was this created because you're operating in an environment with <Ansible-2.2?

    Since [efs](https://docs.ansible.com/ansible/efs_module.html) was only introduced then

- Was there some other instigating factor to make this role?

**Comment by simplyadrian** [comment]
we like the ability to define and compose our stacks in CFN. We leverage ansible more templating in these cases.

**Comment by tomislacker** [comment]
Understood, I can certainly respect that and was just curious. Thanks @simplyadrian for the quick response!
